### PR TITLE
Add world Id component, testing components and the staking component in the directory, please check and review

### PR DESCRIPTION
**Pull request by derek2403**

### CODE REVIEW

**Review by JingYuan0926 — COMMENTED** [review]
The provided code files are well-written and functional, showcasing a solid understanding of the respective tasks. The WorldIDLogin component integrates WorldID verification seamlessly, with effective backend communication and state handling, ensuring a smooth user experience and clear redirection logic. The AutoMultiChainBridgeTransfer file demonstrates robust logic for automating transfers across Ethereum, Optimism, and Polygon, with well-structured configuration objects and user-friendly UI for displaying wallets and transaction results. The Home Page efficiently integrates the WorldIDLogin component in a minimalistic and functional design, serving as a straightforward entry point for user interactions. Lastly, the SendPolygonFunds component is thoughtfully implemented, with clean logic for wallet balance checks and Polygon fund transfers, effective error handling, and a user-friendly interface. All files are well-structured, ready for testing, and good to proceed with integration. Excellent work!

**Review by JingYuan0926 — COMMENTED** [review]
After reviewing the files again, I think removing the WorldIDLogin component might be a better approach. While the integration is clean and functional, the reliance on WorldID for user verification may add unnecessary complexity, especially if simpler or more universal authentication methods could suffice.

**Review by JingYuan0926 — COMMENTED** [review]
Next, update the transfer methods in AutoMultiChainBridgeTransfer and SendPolygonFunds to use private keys retrieved from local storage. Ensure robust error handling and consider encrypting the key for added security. Once these changes are implemented and tested, the files should be good to proceed. Let me know if you need help with the encryption logic or updating the transfer methods!

**Review by JingYuan0926 — COMMENTED** [review]
For the AutoMultiChainBridgeTransfer implementation, shifting to a cross-chain intent-based approach instead of the current wallet-to-wallet transfer logic would be more efficient and aligned with modern cross-chain solutions.

**Comment by derek2403** [comment]
To update the AutoMultiChainBridgeTransfer and SendPolygonFunds methods, the private keys should be retrieved securely from local storage, with robust error handling and encryption implemented for added security. The private key should be encrypted using a secure algorithm, such as AES, before being stored, and decrypted only when needed for the transfer process. During the retrieval process, ensure validation of the key’s presence and format, and handle errors gracefully if the key is missing, invalid, or fails decryption. The updated transfer methods should use the decrypted private key to sign transactions securely, ensuring no sensitive information is exposed. Comprehensive error handling should be in place for scenarios such as missing keys or transaction failures, providing clear logs and user-friendly feedback. These changes should enhance security and reliability, making the files ready for production after thorough testing of all edge cases and functionalities. Let me know if assistance is needed with the encryption logic or testing!

**Pull request merged**
