### PR TITLE
add consolidate and check

### PR DESCRIPTION
**Pull request by derek2403**

### CODE REVIEW

**Review by JingYuan0926 — COMMENTED** [review]
The code is well-written and functions effectively, but it would benefit from clearer documentation and naming to enhance readability and maintainability. Adding brief comments or docstrings to explain the purpose of key sections, functions, and classes would make it easier for others to understand. So what does it do

**Review by JingYuan0926 — COMMENTED** [review]
The structure is clear and well-organized. To ensure its functionality, I recommend testing with lightweight chains like Polygon (Amoy), Optimism (Sepolia), and Arbitrum (if added later), as they are faster and cheaper for testing. If all works well, you can expand the list to include other popular EVM chains like Ethereum Mainnet, Binance Smart Chain, and Avalanche.

**Review by JingYuan0926 — COMMENTED** [review]
How about this: we focus on the front-end design first while I take care of the back-end and structure things out before we dive into implementation? This way, we can ensure the design and functionality align perfectly before coding. Additionally, I noticed the current dashboard design might not be as appealing, it could benefit from a more modern and polished UI. We could consider using NextUI throughout for a consistent and clean look, as it simplifies styling and component handling. Let me know your thoughts, and we can plan the workflow accordingly!

**Comment by derek2403** [comment]
Sure! That sounds like a great plan. Focusing on the front-end design first is a smart approach, as it allows us to ensure the UI/UX aligns perfectly with the functionality before diving into implementation. I agree that the current dashboard design could be improved, and using NextUI is an excellent choice—it’ll definitely help achieve a modern, polished, and consistent look while simplifying styling and component handling. Let me know how you’d like to proceed with the workflow, and we can collaborate effectively to bring this vision to life!

**Pull request merged**
