### PR TITLE
I will continue working on my branch, please give me some suggestions on what I want to do first? 

### PR DESCRIPTION
**Pull request by derek2403**

### CODE REVIEW

**Review by JingYuan0926 — COMMENTED** [review]
The merging process is complete, and there are no errors or conflicts. Everything has been successfully integrated without issues.

**Comment by derek2403** [comment]
Okay, I will continue now. Hope I can finish by tonight

**Review by JingYuan0926 — COMMENTED** [review]
Can you now add the AI-powered transfer fund functionality to my code, allowing users to seamlessly transfer funds after creating a wallet.

**Review by derek2403 — COMMENTED** [review]
I will fix abit of the UI part

**Comment by derek2403** [comment]
Ok i will do the requested part and finish by tonight.

**Pull request merged**
