### PR TITLE
Implement account availability check in CreateWallet component

### PR DESCRIPTION
**Pull request by JingYuan0926**
- Added state management for account ID, checking status, and availability.
- Introduced a new function to check account availability using NEAR RPC.
- Updated wallet generation logic to use the full account ID format.
- Enhanced UI to allow users to input desired account names and check their availability before wallet generation.
- Improved user feedback with availability messages and button states based on checking status.

While the core functionality is fully implemented and operational, the UI/UX design is still under development and will be improved in the next iteration. The current version focuses on ensuring the main features work seamlessly, with further interface enhancements planned for next updates.

### CODE REVIEW

**Review by derek2403 — COMMENTED** [review]
The proposed changes are indeed significant. If a wallet already exists, it would be impossible to create a new one. This would be a very useful feature. Please let me know your thoughts on this. Thank you.

**Comment by JingYuan0926** [comment]
Yes, if a wallet already exists, the system will indicate a failure to create a new one. This ensures that duplicate wallets cannot be created. Let me know if there are any further considerations. Thank you!

**Review by JingYuan0926 — COMMENTED** [review]
I think you should focus on designing the UI/UX now that the feature is already completed. Ensuring a smooth and intuitive user interface will significantly enhance the user experience.

**Comment by derek2403** [comment]
Thank you for your suggestion! Now that the feature development is complete, I agree that focusing on the UI/UX is crucial. A well-designed user interface and an intuitive user experience can significantly impact how users perceive and interact with the product. My plan is to ensure that the interface is not only visually appealing but also easy to navigate, keeping user convenience at the forefront. I’ll work on refining the layout, improving accessibility, and streamlining the overall flow of the application. If you have any specific feedback, ideas, or examples that you think would enhance the design further, I’d love to hear your thoughts.

**Pull request merged**
